export const CATEGORIES = [
  { name: "Drama", value: "drama" },
  { name: "Comedy", value: "comedy" },
  { name: "Horror", value: "horror" },
  { name: "Romance", value: "romance" },
  { name: "Sci-fi", value: "sci-fi" },
  { name: "Fantasy", value: "fantasy" },
  { name: "Humor", value: "humor" },
  { name: "Action", value: "action" },
  { name: "Thriller", value: "thriller" },
  { name: "Supernatural", value: "supernatural" },
  { name: "Adventure", value: "adventure" },
  { name: "Mystery", value: "mystery" },
  { name: "Western", value: "western" },
  { name: "History", value: "history" },
  { name: "Crime", value: "crime" },
  { name: "Fanfiction", value: "fanfiction" },
];

export const COPYRIGHTS = [
  { name: "Public Domain", value: "public domain" },
  { name: "All Rights Reserved", value: "all rights reserved" },
  { name: "Creative Commons", value: "creative commons" },
];

export const LANGUAGES = [
  { name: "Afar", value: "aa" },
  { name: "Abkhazian", value: "ab" },
  { name: "Avestan", value: "ae" },
  { name: "Afrikaans", value: "af" },
  { name: "Akan", value: "ak" },
  { name: "Amharic", value: "am" },
  { name: "Aragonese", value: "an" },
  { name: "Arabic", value: "ar" },
  { name: "Assamese", value: "as" },
  { name: "Avaric", value: "av" },
  { name: "Aymara", value: "ay" },
  { name: "Azerbaijani", value: "az" },
  { name: "Bashkir", value: "ba" },
  { name: "Belarusian", value: "be" },
  { name: "Bulgarian", value: "bg" },
  { name: "Bihari", value: "bh" },
  { name: "Bislama", value: "bi" },
  { name: "Bambara", value: "bm" },
  { name: "Bengali", value: "bn" },
  { name: "Tibetan", value: "bo" },
  { name: "Breton", value: "br" },
  { name: "Bosnian", value: "bs" },
  { name: "Catalan", value: "ca" },
  { name: "Chechen", value: "ce" },
  { name: "Chamorro", value: "ch" },
  { name: "Corsican", value: "co" },
  { name: "Cree", value: "cr" },
  { name: "Czech", value: "cs" },
  { name: "Old Church Slavonic", value: "cu" },
  { name: "Chuvash", value: "cv" },
  { name: "Welsh", value: "cy" },
  { name: "Danish", value: "da" },
  { name: "German", value: "de" },
  { name: "Divehi", value: "dv" },
  { name: "Dzongkha	", value: "dz" },
  { name: "Ewe", value: "ee" },
  { name: "Greek", value: "el" },
  { name: "English", value: "en" },
  { name: "Esperanto", value: "eo" },
  { name: "Spanish", value: "es" },
  { name: "Estonian", value: "et" },
  { name: "Basque", value: "eu" },
  { name: "Persian", value: "fa" },
  { name: "Fulah", value: "ff" },
  { name: "Finnish", value: "fi" },
  { name: "Fijian", value: "fj" },
  { name: "Faroese", value: "fo" },
  { name: "French", value: "fr" },
  { name: "Western Frisian", value: "fy" },
  { name: "Irish", value: "ga" },
  { name: "Scottish Gaelic", value: "gd" },
  { name: "Galician", value: "gl" },
  { name: "Guarani", value: "gn" },
  { name: "Gujarati", value: "gu" },
  { name: "Manx", value: "gv" },
  { name: "Hausa", value: "ha" },
  { name: "Hebrew", value: "he" },
  { name: "Hindi", value: "hi" },
  { name: "Hiri Motu", value: "ho" },
  { name: "Croatian", value: "hr" },
  { name: "Haitian", value: "ht" },
  { name: "Hungarian", value: "hu" },
  { name: "Armenian", value: "hy" },
  { name: "Herero", value: "hz" },
  { name: "Interlingua", value: "ia" },
  { name: "Indonesian", value: "id" },
  { name: "Interlingue", value: "ie" },
  { name: "Igbo", value: "ig" },
  { name: "Sichuan Yi", value: "ii" },
  { name: "Inupiaq", value: "ik" },
  { name: "Ido", value: "io" },
  { name: "Icelandic", value: "is" },
  { name: "Italian", value: "it" },
  { name: "Inuktitut", value: "iu" },
  { name: "Japanese", value: "ja" },
  { name: "Javanese", value: "jv" },
  { name: "Georgian", value: "ka" },
  { name: "Kongo", value: "kg" },
  { name: "Kikuyu", value: "ki" },
  { name: "Kwanyama", value: "kj" },
  { name: "Kazakh", value: "kk" },
  { name: "Greenlandic", value: "kl" },
  { name: "Khmer", value: "km" },
  { name: "Kannada", value: "kn" },
  { name: "Korean", value: "ko" },
  { name: "Kanuri", value: "kr" },
  { name: "Kashmiri", value: "ks" },
  { name: "Kurdish", value: "ku" },
  { name: "Komi", value: "kv" },
  { name: "Cornish", value: "kw" },
  { name: "Kirghiz", value: "ky" },
  { name: "Latin", value: "la" },
  { name: "Luxembourgish", value: "lb" },
  { name: "Ganda", value: "lg" },
  { name: "Limburgish", value: "li" },
  { name: "Lingala", value: "ln" },
  { name: "Lao", value: "lo" },
  { name: "Lithuanian", value: "lt" },
  { name: "Luba", value: "lu" },
  { name: "Latvian", value: "lv" },
  { name: "Malagasy", value: "mg" },
  { name: "Marshallese", value: "mh" },
  { name: "Māori", value: "mi" },
  { name: "Macedonian", value: "mk" },
  { name: "Malayalam", value: "ml" },
  { name: "Mongolian", value: "mn" },
  { name: "Moldavian", value: "mo" },
  { name: "Marathi", value: "mr" },
  { name: "Malay", value: "ms" },
  { name: "Maltese", value: "mt" },
  { name: "Burmese", value: "my" },
  { name: "Nauru", value: "na" },
  { name: "Norwegian Bokmål", value: "nb" },
  { name: "North Ndebele", value: "nd" },
  { name: "Nepali", value: "ne" },
  { name: "Ndonga", value: "ng" },
  { name: "Dutch", value: "nl" },
  { name: "Norwegian Nynorsk", value: "nn" },
  { name: "Norwegian", value: "no" },
  { name: "South Ndebele", value: "nr" },
  { name: "Navajo", value: "nv" },
  { name: "Chichewa", value: "ny" },
  { name: "Occitan", value: "oc" },
  { name: "Ojibwa", value: "oj" },
  { name: "Oromo", value: "om" },
  { name: "Oriya", value: "or" },
  { name: "Ossetian", value: "os" },
  { name: "Panjabi", value: "pa" },
  { name: "Pāli", value: "pi" },
  { name: "Polish", value: "pl" },
  { name: "Pashto", value: "ps" },
  { name: "Portuguese", value: "pt" },
  { name: "Quechua", value: "qu" },
  { name: "Reunionese", value: "rc" },
  { name: "Romansh", value: "rm" },
  { name: "Kirundi", value: "rn" },
  { name: "Romanian", value: "ro" },
  { name: "Russian", value: "ru" },
  { name: "Kinyarwanda", value: "rw" },
  { name: "Sanskrit", value: "sa" },
  { name: "Sardinian", value: "sc" },
  { name: "Sindhi", value: "sd" },
  { name: "Northern Sami", value: "se" },
  { name: "Sango", value: "sg" },
  { name: "Serbo-Croatian", value: "sh" },
  { name: "Sinhalese", value: "si" },
  { name: "Slovak", value: "sk" },
  { name: "Slovenian", value: "sl" },
  { name: "Samoan", value: "sm" },
  { name: "Shona", value: "sn" },
  { name: "Somali", value: "so" },
  { name: "Albanian", value: "sq" },
  { name: "Serbian", value: "sr" },
  { name: "Swati", value: "ss" },
  { name: "Sotho", value: "st" },
  { name: "Sundanese", value: "su" },
  { name: "Swedish", value: "sv" },
  { name: "Swahili", value: "sw" },
  { name: "Tamil", value: "ta" },
  { name: "Telugu", value: "te" },
  { name: "Tajik", value: "tg" },
  { name: "Thai", value: "th" },
  { name: "Tigrinya", value: "ti" },
  { name: "Turkmen", value: "tk" },
  { name: "Tagalog", value: "tl" },
  { name: "Tswana", value: "tn" },
  { name: "Tonga", value: "to" },
  { name: "Turkish", value: "tr" },
  { name: "Tsonga", value: "ts" },
  { name: "Tatar", value: "tt" },
  { name: "Twi", value: "tw" },
  { name: "Tahitian", value: "ty" },
  { name: "Uighur", value: "ug" },
  { name: "Ukrainian", value: "uk" },
  { name: "Urdu", value: "ur" },
  { name: "Uzbek", value: "uz" },
  { name: "Venda", value: "ve" },
  { name: "Viêt Namese", value: "vi" },
  { name: "Volapük", value: "vo" },
  { name: "Walloon", value: "wa" },
  { name: "Wolof", value: "wo" },
  { name: "Xhosa", value: "xh" },
  { name: "Yiddish", value: "yi" },
  { name: "Yoruba", value: "yo" },
  { name: "Zhuang", value: "za" },
  { name: "Chinese", value: "zh" },
  { name: "Zulu", value: "zu" },
];

export const STATUS = [
  { name: "In Progress", value: "in progress" },
  { name: "In Hiatus", value: "in hiatus" },
  { name: "Completed", value: "completed" },
];

// TYPES
export const types = {
  GET_PROFILE: "GET_PROFILE",
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  GET_STORY: "GET_STORY",
  GET_USER_STORIES: "GET_USER_STORIES",
  GET_HOME_STORIES: "GET_HOME_STORIES",
  GET_FEATURED_STORIES: "GET_FEATURED_STORIES",
  GET_USERS_FROM_SEARCH: "GET_USERS_FROM_SEARCH",
  GET_POPULAR_USERS: "GET_POPULAR_USERS",
  GET_FAVORITE_STORIES: "GET_FAVORITE_STORIES",
  ADD_STORY: "ADD_STORY",
  EDIT_STORY: "EDIT_STORY",
  DELETE_STORY: "DELETE_STORY",
  GET_STORIES_FROM_SEARCH: "GET_STORIES_FROM_SEARCH",
  IS_STORY_FAVORITE: "IS_STORY_FAVORITE",
  IS_CHARACTER_FAVORITE: "IS_CHARACTER_FAVORITE",
  IS_FOLLOWING: "IS_FOLLOWING",
  GET_CHAPTER: "GET_CHAPTER",
  ADD_CHAPTER: "ADD_CHAPTER",
  EDIT_CHAPTER: "EDIT_CHAPTER",
  DELETE_CHAPTER: "DELETE_CHAPTER",
  GET_CHAPTERS: "GET_CHAPTERS",
  ADD_CHARACTER: "ADD_CHARACTER",
  GET_CHARACTER: "GET_CHARACTER",
  EDIT_CHARACTER: "EDIT_CHARACTER",
  DELETE_CHARACTER: "DELETE_CHARACTER",
  GET_USER_CHARACTERS: "GET_USER_CHARACTERS",
  GET_POPULAR_CHARACTERS: "GET_POPULAR_CHARACTERS",
  GET_CHARACTER_COMMENTS: "GET_CHARACTER_COMMENTS",
  GET_CHARACTERS_FROM_SEARCH: "GET_CHARACTERS_FROM_SEARCH",
  GET_USER_LOCATIONS: "GET_USER_LOCATIONS",
  GET_FAVORITE_CHARACTERS: "GET_FAVORITE_CHARACTERS",
  GET_STORY_CHARACTERS: "GET_STORY_CHARACTERS",
  ADD_LOCATION: "ADD_LOCATION",
  GET_LOCATION: "GET_LOCATION",
  EDIT_LOCATION: "EDIT_LOCATION",
  DELETE_LOCATION: "DELETE_LOCATION",
  GET_COMMENTS: "GET_COMMENTS",
  GET_FAVORITE_AUTHORS: "GET_FAVORITE_AUTHORS",
  GET_STORY_LOCATIONS: "GET_STORY_LOCATIONS",
  GET_FOLLOWERS: "GET_FOLLOWERS",
  DISPATCH_ERROR: "DISPATCH_ERROR",
  SUBMIT_COMMENT: "SUBMIT_COMMENT",
  RATE_COMMENT: "RATE_COMMENT",
  GET_NOTIFICATIONS: "GET_NOTIFICATIONS",
};

export const GET_PROFILE = "GET_PROFILE";
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";

export const GET_STORY = "GET_STORY";
export const GET_USER_STORIES = "GET_USER_STORIES";
export const GET_FAVORITE_STORIES = "GET_FAVORITE_STORIES";
export const ADD_STORY = "ADD_STORY";
export const EDIT_STORY = "EDIT_STORY";
export const DELETE_STORY = "DELETE_STORY";
export const IS_STORY_FAVORITE = "IS_STORY_FAVORITE";

export const GET_CHAPTER = "GET_CHAPTER";
export const ADD_CHAPTER = "ADD_CHAPTER";
export const EDIT_CHAPTER = "EDIT_CHAPTER";
export const DELETE_CHAPTER = "DELETE_CHAPTER";
export const GET_CHAPTERS = "GET_CHAPTERS";

export const ADD_CHARACTER = "ADD_CHARACTER";
export const GET_CHARACTER = "GET_CHARACTER";
export const EDIT_CHARACTER = "EDIT_CHARACTER";
export const GET_USER_CHARACTERS = "GET_USER_CHARACTERS";
export const GET_USER_LOCATIONS = "GET_USER_LOCATIONS";
export const GET_FAVORITE_CHARACTERS = "GET_FAVORITE_CHARACTERS";
export const GET_STORY_CHARACTERS = "GET_STORY_CHARACTERS";

export const ADD_LOCATION = "ADD_LOCATION";

export const GET_FAVORITE_AUTHORS = "GET_FAVORITE_AUTHORS";
export const GET_FOLLOWERS = "GET_FOLLOWERS";

export const DISPATCH_ERROR = "DISPATCH_ERROR";
